version: "3.8"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    expose:
      - "5252"
    deploy:
      replicas: 2  # Number of API servers
      restart_policy:
        condition: any

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    expose:
      - "9000"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end